package libsc

val db: Map<Char, Char> = mapOf(
    'a' to '`',
    'b' to '-',
    'c' to ')',
    'd' to '/',
    'e' to '?',
    'f' to '^',
    'g' to '#',
    'h' to '!',
    'i' to ';',
    'j' to '.',
    'k' to '\\',
    'l' to '~',
    'm' to '&',
    'n' to '*',
    'o' to '(',
    'p' to '@',
    'q' to '"',
    'r' to '>',
    's' to '<',
    't' to '[',
    'u' to ']',
    'v' to '{',
    'w' to '}',
    'x' to '|',
    'y' to '+',
    'z' to '_',
    ' ' to ',',
    ',' to ':',
    '.' to '=',
    '!' to 'a',
    '?' to 'b',
    '\n' to 'c',
    '\'' to 'd',
    '(' to 'e',
    ')' to 'f',
    '1' to 'g',
    '2' to 'h',
    '3' to 'i',
    '4' to 'j',
    '5' to 'k',
    '6' to 'l',
    '7' to 'm',
    '8' to 'n',
    '9' to 'o',
    '0' to 'p',
    '-' to 'q',
    '&' to 'r',
    ':' to 's',
    ';' to 't',
    '"' to 'u',
    '\\' to 'v',
    '/' to 'w',
    '~' to 'x'
)